### ISSUE TITLE
some question about semi-supervised learning

### ISSUE THREAD

**Issue by AndyYuan96** [PointsCoder/ONCE_Benchmark#1]
Hi, @PointsCoder , thanks for sharing the source code, I have one question about the code after reading, for 3dioumatch, why you use cls_score as nms_score ? does't it give better result? as now many detector use iou score as nms score

**Comment by PointsCoder** [comment]
In my experiments, cls score is better than iou score. It is probably because the iou head didn't perform well. I didn't investigate this part deeply.

**Comment by Divadi** [comment]
Hi, I had a few questions as well:
For example, in mean_teacher_second_medium.yaml, NUM_EPOCHS is 75, with a comment saying this is 3 epochs for medium. I was wondering how that was the case (I thought 500k samples for medium, 5k samples for train data, so 75 * 5k = 375k? (similar question for small & large) - in your experience, did # of epochs affect final numbers? How about other parameters like EMA_EPOCH, UD_BATCH_SIZE_PER_GPU, lr schedule?

Thank you!

**Comment by PointsCoder** [comment]
@Divadi An example:

UD_BATCH_SIZE_PER_GPU=4 & LD_BATCH_SIZE_PER_GPU=1
That means the total batch size is 5, and a batch contains 1 labeled scene in training and 4 unlabeled scenes in the U_medium set.

NUM_EPOCHS=75
We count the epochs solely based on labeled data, so one epoch means we iterate all the training scenes one time. Furthermore, when we iterate 5k labeled data, considering the above batch size, we actually iterate 20k unlabeled scenes at the same time. U_medium has 500k unlabeled scenes in total, so it takes 25 epochs in our definition to iterate over the whole set. 75/25=3 epoch actually for unlabeled data.

EMA_EPOCH
This is a parameter for EMA (Exponential Moving Average) ramp up.

**Comment by Divadi** [comment]
Ah! I understand!

Did you also try adjusting # of epochs/UD_BATCH_SIZE_PER_GPU, and if so, how did they affect performance?  (I'm just trying to get a feel for some hyperparameters that you may have tuned already)

**Comment by PointsCoder** [comment]
I didn't tune this hyperparameter. I will appreciate it if you could give it a try :）

**Comment by Divadi** [comment]
I see, got it
If you are familiar, I would appreciate it if you could take a look at the 2D-to-3D projection issue on the devkit code, but if not, thank you regardless : )

**Comment by AndyYuan96** [comment]
> In my experiments, cls score is better than iou score. It is probably because the iou head didn't perform well. I didn't investigate this part deeply.

if the iou head not perform well, the method looks useless, as iou score should have better quality than cls score😂。

**Comment by AndyYuan96** [comment]
for self-supervised learning， does it ok to train only 20 epochs？， as in image， they train many epochs， which is much more than 20 epochs。

**Comment by PointsCoder** [comment]
@AndyYuan96 I didn't reproduce the self-supervised part. The official code may be released later.
