### ISSUE TITLE
About the results of ONCE Benchmark

### ISSUE THREAD

**Issue by Michael-Shaw** [PointsCoder/ONCE_Benchmark#10]
How can I continue to obtain the results of the ONCE test split data after the 'ICCV 2021 Workshop SSLAD Track 2 - 3D Object Detection' competition is over? 
Thanks！

**Comment by PointsCoder** [comment]
We will open a permanent phase on codalab after the competition.

**Comment by Michael-Shaw** [comment]
@PointsCoder Thinks!

**Comment by PointsCoder** [comment]
Closed if no other questions.
