### ISSUE TITLE
EMA for 3D IoU Match

### ISSUE THREAD

**Issue by wyddmw** [PointsCoder/ONCE_Benchmark#11]
Hi, I was reading this project recently and I found that there is something different from the original implementation of the 3D IoU Match. In the paper of 3D IoU Match, the EMA was applied for updating the teacher model which was not used in your project. I  also realized that in your paper ONCE, the description of the 3D IoU Match also missed the EMA part in figure3. I was wondering whether this is the reason for the less competitive performance of the 3D IoU Match as mentioned in the paper ONCE. Anyway, thanks for this awesome work.

**Comment by PointsCoder** [comment]
@wyddmw I tried EMA before but it seems to work only with consistency regularization. 3DIoUMatch didn't include consistency loss and I cannot reproduce the results with only EMA and no consistency.

**Comment by PointsCoder** [comment]
Closed if no other questions.
