### ISSUE TITLE
When will the permanent phase start?

### ISSUE THREAD

**Issue by Michael-Shaw** [PointsCoder/ONCE_Benchmark#12]
@PointsCoder Thank you for the excellent ONCE dataset and baseline. Now the 'ICCV 2021 Workshop SSLAD Track 2 - 3D Object Detection' competition is over. When will the permanent phase start, and when will the results of the test set be available? Thanks a lot.

**Comment by PointsCoder** [comment]
@Michael-Shaw We are working on this now. It will come very soon and I will notify you in this issue when it starts.

**Comment by PointsCoder** [comment]
@Michael-Shaw Test phase has restarted at https://competitions.codalab.org/competitions/33236

**Comment by Michael-Shaw** [comment]
@PointsCoder Thank you for your work! I still have some questions about the new phase. Does the new test phase share the same leaderboard as the previous one? If yes, does this mean all the previous rules are also allowed? Will there be a leaderboard that only presents single-model multi-classes 3D object detection?

**Comment by PointsCoder** [comment]
@Michael-Shaw The leader board will contain all sorts of detection methods. We are not able to check whether a method is a single model or not. For research, you can simply cite those published single-model papers and ignore the rest.

**Comment by Michael-Shaw** [comment]
> @Michael-Shaw The leader board will contain all sorts of detection methods. We are not able to check whether a method is a single model or not. For research, you can simply cite those published single-model papers and ignore the rest.

Thank you for your reply！

**Comment by DeclK** [comment]
This Link https://competitions.codalab.org/competitions/33236 is no longer available now. How can I get the test split result?
