### ISSUE TITLE
About SHIFT_COOR parameter in waymo-to-once setting

### ISSUE THREAD

**Issue by weiyithu** [PointsCoder/ONCE_Benchmark#13]
In tools/cfgs/once_models/uda_models/waymo_to_once/secondiou_waymo_origin.yaml, the SHIFT_COOR parameter is set to [0,0,0] and [0,0,1.6] is noted. However, the origin of corrdinates in Waymo point cloud is on the ground while that in ONCE point cloud is the LiDAR sensor. Thus, there exists origin shift between two datasets and why you use [0,0,0]. Thanks!

**Comment by PointsCoder** [comment]
@weiyithu I didn't notice that. I can merge your configs if you attain a better result.

**Comment by weiyithu** [comment]
After changing [0,0,0] to [0,0,1.6], we will get much better results. Moreover, there may be a bug in once_target_dataset.py:  you should add SHIFT_COOR on the prediction boxes, which is similat to the nuscenes_dataset.py
<img width="340" alt="微信图片_20211206112804" src="https://user-images.githubusercontent.com/32617425/144782575-351a6a46-880d-42ee-b643-11c2aea30a5b.png">
