### ISSUE TITLE
Hi, will you release the pre-trained model? I can not get the samle result of centerpoints as the paper. The performers is poor than paper.

### ISSUE THREAD

**Issue by mrqrs** [PointsCoder/ONCE_Benchmark#14]

**Comment by PointsCoder** [comment]
@mrqrs We cannot release the checkpoint, but I reproduced the results before I release this repo. What result did you get, and did you change some of the configs?

**Comment by mrqrs** [comment]
I use 4 3090 gpus  with batch size 32 and use the centerpoints.yaml to train the model and did not change the config file. The result of three class are all loser than paper. The result is:
![image](https://user-images.githubusercontent.com/26370029/146641583-3e05b0be-4d95-443c-9e2c-ed7117df86ea.png)

**Comment by mrqrs** [comment]
> @mrqrs We cannot release the checkpoint, but I reproduced the results before I release this repo. What result did you get, and did you change some of the configs?

I use 4 3090 gpus with batch size 32 and use the centerpoints.yaml to train the model and did not change the config file. The result of three class are all loser than paper. The result is:
![image](https://user-images.githubusercontent.com/26370029/146641630-0048a31e-38d3-4ccc-b8f9-dbe7a9574bb5.png)

**Comment by mrqrs** [comment]
> @mrqrs We cannot release the checkpoint, but I reproduced the results before I release this repo. What result did you get, and did you change some of the configs?

I have used 4 3090 gpus with batch size 32 and the centerpoints.yaml to train the model and did not change the config file. The result of three class  is loser than paper. The result is:

**Comment by mrqrs** [comment]
> 

![image](https://user-images.githubusercontent.com/26370029/146642281-49b34463-b5d2-491f-a2d8-efb568a8c7c0.png)

**Comment by PointsCoder** [comment]
@mrqrs We were using 8 gpus with batch size 32 for training. 4 3090 gpus should be batch size 16 without changing the yaml file? If the batch size is different, maybe you can try different training lr and epochs?

**Comment by mrqrs** [comment]
> @mrqrs We were using 8 gpus with batch size 32 for training. 4 3090 gpus should be batch size 16 without changing the yaml file? If the batch size is different, maybe you can try different training lr and epochs?

You trained the model with 8 gpus with batch size 32. (batch size 4 per gpu? or batch size 32 per gpu?) The args "batch_size" in openpcdet is for all gpus (for one gpu is : batch_size / gpu_number) while training the model with multi-gpus.

**Comment by mrqrs** [comment]
> @mrqrs We were using 8 gpus with batch size 32 for training. 4 3090 gpus should be batch size 16 without changing the yaml file? If the batch size is different, maybe you can try different training lr and epochs?

And i used the pytorch 1.8.0, cuda 11.1, pcdet 0.3.0 and spconv 1.2.1. Will the environment affect the result?

**Comment by PointsCoder** [comment]
@mrqrs We specify bs_per_gpu=4 in the yaml file. If we both use batch size 32, I think the problem may not happen here. Did you incorporate our code into your pcdet repo? Can you just **re-compile** this repo and train the models with this repo? I'm not sure whether there are any differences with pcdet 0.3.0. I think other environments (pytorch, cuda, spconv version) are not sensitive.

**Comment by mrqrs** [comment]
> 

Yes, I cloned  and compiled this repo. I did not use the original pcdet repo.

**Comment by PointsCoder** [comment]
@mrqrs That's too weird. Did you try training it multiple times or evaluating checkpoints at different epochs? If you still cannot reproduce the results, I may try getting a checkpoint to you, but it's complicated and takes time.

**Comment by PointsCoder** [comment]
![image](https://user-images.githubusercontent.com/28640612/146643609-4b360bf9-eaf7-4cd0-b656-99c041eab30c.png)
If you use 4 gpus, please change bs_per_gpu =8, use this command and do not add any other args. Try running it multiple times.

**Comment by PointsCoder** [comment]
![image](https://user-images.githubusercontent.com/28640612/146643671-14881c40-df55-463f-829e-bf40b27931c7.png)
Change this to 8 in centerpoints.yaml.

**Comment by mrqrs** [comment]
> @mrqrs That's too weird. Did you try training it multiple times or evaluating checkpoints at different epochs? If you still cannot reproduce the results, I may try getting a checkpoint to you, but it's complicated and takes time.

Ok, thanks for your reply. I juste tested withe epoch 80. I will test with different checkpoint and train model with your suggested   method.

**Comment by PointsCoder** [comment]
@mrqrs Hi, can you reproduce the results now?

**Comment by mrqrs** [comment]
> @mrqrs Hi, can you reproduce the results n

> @mrqrs Hi, can you reproduce the results now?

No, the result is poor than paper. The result is:
![image](https://user-images.githubusercontent.com/26370029/147466729-858a344e-97cb-4014-97bc-5166261aa3b3.png)

**Comment by mrqrs** [comment]
> @mrqrs Hi, can you reproduce the results now?

**Comment by mrqrs** [comment]
> @mrqrs Hi, can you reproduce the results now?

Hi, how do i submit the test result?  Is this submit [web](https://competitions.codalab.org/competitions/33236#results) still avaliable? I submitted the code outputed result.pkl to the web. And i can not see the result. It seems to be in the process of scoring with a long time.

**Comment by PointsCoder** [comment]
> > @mrqrs Hi, can you reproduce the results n
> 
> > @mrqrs Hi, can you reproduce the results now?
> 
> No, the result is poor than paper. The result is: ![image](https://user-images.githubusercontent.com/26370029/147466729-858a344e-97cb-4014-97bc-5166261aa3b3.png)

@mrqrs I can share a checkpoint with reproduced results with you. The download link is https://drive.google.com/file/d/1lj8smqo3fc9qVz7eanjuNXyhskPy3jez/view?usp=sharing.

Plz carefully check where the problem is yourself.

**Comment by PointsCoder** [comment]
> > @mrqrs Hi, can you reproduce the results now?
> 
> Hi, how do i submit the test result? Is this submit [web](https://competitions.codalab.org/competitions/33236#results) still avaliable? I submitted the code outputed result.pkl to the web. And i can not see the result. It seems to be in the process of scoring with a long time.

Plz strictly follow the submission format mentioned on the website:

![image](https://user-images.githubusercontent.com/28640612/147648435-89de8129-6d3f-44fa-80b0-a2e849d60c72.png)

**Comment by mrqrs** [comment]
> > > @mrqrs Hi, can you reproduce the results n
> > 
> > 
> > > @mrqrs Hi, can you reproduce the results now?
> > 
> > 
> > No, the result is poor than paper. The result is: ![image](https://user-images.githubusercontent.com/26370029/147466729-858a344e-97cb-4014-97bc-5166261aa3b3.png)
> 
> @mrqrs I can share a checkpoint with reproduced results with you. The download link is https://drive.google.com/file/d/1lj8smqo3fc9qVz7eanjuNXyhskPy3jez/view?usp=sharing.
> 
> Plz carefully check where the problem is yourself.

Thanks for your reply. I will test it again. Thanks.

**Comment by PointsCoder** [comment]
Closed if no other problems.
