### ISSUE TITLE
About Imageset files

### ISSUE THREAD

**Issue by Poley97** [PointsCoder/ONCE_Benchmark#17]
I have downloaded and unpacked the whole ONCE Dataset and have cloned this repo, but I still can't find the ImageSets folder and any description or information about it.  How can I get the ImageSets folder? Thanks a lot!

**Comment by PointsCoder** [comment]
@Poley97 You can find ImageSet at https://github.com/once-for-auto-driving/once_devkit

**Comment by Poley97** [comment]
Thank you so much for your reply!
