### ISSUE TITLE
Where the code to transform the original ONCE lidar point clouds to unified normative coordinate?

### ISSUE THREAD

**Issue by ideasplus** [PointsCoder/ONCE_Benchmark#24]
Hi

The coordinate of original ONCE lidar point clouds is **x pointing left, y pointing backwards**. However, I can't find the code to explicitly transform the once lidar coordinate to the unified normative coordinate as the openpcdet documentation states.

The getitem method of once
https://github.com/PointsCoder/ONCE_Benchmark/blob/aebe9dc8ceefb198719aa6938a97115f55add794/pcdet/datasets/once/once_dataset.py#L126-L153

The get_lidar method of once
https://github.com/PointsCoder/ONCE_Benchmark/blob/aebe9dc8ceefb198719aa6938a97115f55add794/pcdet/datasets/once/once_dataset.py#L73-L74

The load_point_cloud method of once
```
def load_point_cloud(self, seq_id, frame_id):
    bin_path = osp.join(self.data_root, seq_id, 'lidar_roof', '{}.bin'.format(frame_id))
    points = np.fromfile(bin_path, dtype=np.float32).reshape(-1, 4)
    return points
```

**Comment by PointsCoder** [comment]
There is no need to transform the existing coordinate to the pcdet coordinate. Both lidar point cloud and 3d boxes are in the x-left y-back coordinate, so literally it will not influence the final detection results.

**Comment by OrangeSodahub** [comment]
@PointsCoder But the coordinate system in pcdet shouldn't be x-front, y-left, z-up ?
