### ISSUE TITLE
question about pointpainting

### ISSUE THREAD

**Issue by BigTeacher-777** [PointsCoder/ONCE_Benchmark#6]
In function point_painting, used_classes are [0,1,2,3,4,5], which differ from the segmentation results of HRNet trained on CityScape. How to modify it? Besides, the definition of "cyclist" differs from the "rider". How to modify it?

**Comment by PointsCoder** [comment]
Mapping CityScape (19 classes) to ONCE:

Car: 14; Bus: 26; Truck 15; Ped.: 12; Cyclist: [13, 18, 19]
