### ISSUE TITLE
About training hardware setting

### ISSUE THREAD

**Issue by qiaozhijian** [PointsCoder/ONCE_Benchmark#7]
Hello. What's the type and number of GPUs when training?
Thank you.

**Comment by ahaheng** [comment]
Hi, you can refer to the paper(https://arxiv.org/abs/2106.11037).

**Comment by qiaozhijian** [comment]
> 
> 
> Hi, you can refer to the paper(https://arxiv.org/abs/2106.11037).

Could you please point it out in paper? Which section and paragraph?

**Comment by qiaozhijian** [comment]
> 
> 
> Hi, you can refer to the paper(https://arxiv.org/abs/2106.11037).

I tried, but failed.

**Comment by ahaheng** [comment]
> > Hi, you can refer to the paper(https://arxiv.org/abs/2106.11037).
> 
> Could you please point it out in paper? Which section and paragraph?

I am sorry. I misread. According to the total batch size(32) and batch_size_per_gpu(4), I think the number of GPUs is 8.

**Comment by qiaozhijian** [comment]
> > > Hi, you can refer to the paper(https://arxiv.org/abs/2106.11037).
> > 
> > 
> > Could you please point it out in paper? Which section and paragraph?
> 
> I am sorry. I misread. According to the total batch size(32) and batch_size_per_gpu(4), I think the number of GPUs is 8.

Nevermind. I'm wondering which type of GPU can load 5 batchs(1 labeled and 4 unlabeled).

**Comment by PointsCoder** [comment]
@qiaozhijian 
We use 8 Tesla V100 (32G). For ssl-training, batch_size 5 will take about 10G GPU memory.

**Comment by qiaozhijian** [comment]
Thank you for your reply.
