### ISSUE TITLE
About DistributedDataParallel model encapsulation

### ISSUE THREAD

**Issue by qiaozhijian** [PointsCoder/ONCE_Benchmark#8]
Hello~I'm wondering why do you encapsulate the DistributedDataParallel  model as follows?
https://github.com/PointsCoder/ONCE_Benchmark/blob/3bc1f3ab2f5715ea9e54ee10250a829876abf563/tools/semi_train.py#L57-L74

**Comment by PointsCoder** [comment]
Errors will happen in DDP if this wrapper is not used.

**Comment by qiaozhijian** [comment]
Thank you for your reply.
